# Generated by Django 3.2.5 on 2021-07-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210710_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
